### ISSUE TITLE
snm 

### ISSUE THREAD

**Issue by androidexx** [FelixFrog/pdfgrabber#105] opened 2024-09-29 13:28 UTC
Some book from snm library display this errore and stop at 99%

Select a book or a comma-separated list of books: 0
Applying toc/labels ---------------------------------------   98% 0:00:01
Traceback (most recent call last):────────┤
  File "C:\Users\xxx\Downloads\PDFGrabber_Launcher-main\PDFGrabber_Launcher-main\main.py", line 280, in <module>
    main()asyeschool                      │
  File "C:\Users\xxx\Downloads\PDFGrabber_Launcher-main\PDFGrabber_Launcher-main\main.py", line 261, in main
    downloadbook()                        │
  File "C:\Users\xxx\Downloads\PDFGrabber_Launcher-main\PDFGrabber_Launcher-main\main.py", line 182, in downloadbook
    pdfpath = utils.downloadbook(service, token, bookid, books[bookid], progressfun)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Downloads\PDFGrabber_Launcher-main\PDFGrabber_Launcher-main\utils.py", line 53, in downloadbook
    pdf = service.downloadbook(token, bookid, data, progress)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Downloads\PDFGrabber_Launcher-main\PDFGrabber_Launcher-main\services\snm.py", line 207, in downloadbook │ HoepliAcademy+                   │
    pdf.set_toc(toc)tore - Saggi Digitali │
  File "C:\Python312\Lib\site-packages\fitz\utils.py", line 1339, in set_toc
    raise ValueError("row %i: page number out of range" % i)
ValueError: row 47: page number out of range
└──────┴──────────────────────────────────┘

**Comment by androidexx** [comment] 2024-09-29 13:38
this too:

Select a book or a comma-separated list of books: 4
Error: can't find the source pdf of the book, resorting to manual rendering
Manual rendering not implemented yet, contact the developer!
Extracting zip ------------------ ---------------------  45% 0:01:01

**Comment by androidexx** [comment] 2024-09-29 13:53
Select a book or a comma-separated list of books: 4
Error: can't find the source pdf of the book, resorting to manual rendering
Manual rendering not implemented yet, contact the developer!
Extracting zip ------------------ ---------------------  45% 0:00:41

**Comment by FelixFrog** [comment] 2024-10-19 18:18
The latest commit (d9b681237e7a356acfacddcaf4f2136dd80135e9) should fix this error, but the rendering might not be complete. Try with this update and let me now if the output has any anomaly

**Comment by FelixFrog** [comment] 2024-10-19 18:20
Duplicate of issue [98](https://github.com/FelixFrog/pdfgrabber/issues/105), closing this one to move the discussion there

**Closed by FelixFrog** 2024-10-19 18:20 UTC
